version: "3"
## -------------------------------------------
## DATEV Specific docker compose configuration
## for JFrog services
## -------------------------------------------
services:

## ---------------
  artifactory:
    image: ${JFROG_DOCKER_REPO}/artifactory-pro:${ARTIFACTORY_VERSION}
    container_name: artifactory
    ports:
     - ${ARTIFACTORY_SERVER_PORT}:${ARTIFACTORY_SERVER_PORT}
    volumes:
     - ${XRAY_MOUNT_ROOT}/artifactory:/var/opt/jfrog/artifactory
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    #networks:
    #  - datev-network
    #environment:
    #  - VIRTUAL_HOST=${ARTIFACTORY_HOSTNAME},${ARTIFACTORY_WILDCARD_HOSTNAME}
    #  - VIRTUAL_PORT=8081
    

  xray-server:
    image: ${JFROG_DOCKER_REPO}/xray-server:${XRAY_VERSION}
    container_name: xray-server
    ports:
      - ${XRAY_SERVER_PORT}:${XRAY_SERVER_PORT}
    depends_on:
      - mongodb
      - postgres
      - rabbitmq
    volumes:
      - "$XRAY_MOUNT_ROOT/xray:/var/opt/jfrog/xray/data"
    environment:
      - "XRAYCONFIGPATH=/var/opt/jfrog/xray/data"
      - "DOCKER_COMPOSE_FLAGS=$DOCKER_COMPOSE_FLAGS"
      - "DOCKER_COMPOSE_XRAY_FLAGS=$DOCKER_COMPOSE_XRAY_SERVER_FLAGS"
    restart: always

  xray-indexer:
    image: ${JFROG_DOCKER_REPO}/xray-indexer:${XRAY_VERSION}
    container_name: xray-indexer
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - "$XRAY_MOUNT_ROOT/xray:/var/opt/jfrog/xray/data"
    environment:
      - "XRAYCONFIGPATH=/var/opt/jfrog/xray/data"
      - "DOCKER_COMPOSE_FLAGS=$DOCKER_COMPOSE_FLAGS"
      - "DOCKER_COMPOSE_XRAY_FLAGS=$DOCKER_COMPOSE_XRAY_INDEXER_FLAGS"
    restart: always

  xray-analysis:
    image: ${JFROG_DOCKER_REPO}/xray-analysis:${XRAY_VERSION}
    container_name: xray-analysis
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - "$XRAY_MOUNT_ROOT/xray:/var/opt/jfrog/xray/data"
    environment:
      - "XRAYCONFIGPATH=/var/opt/jfrog/xray/data"
      - "DOCKER_COMPOSE_FLAGS=$DOCKER_COMPOSE_FLAGS"
      - "DOCKER_COMPOSE_XRAY_FLAGS=$DOCKER_COMPOSE_XRAY_ANALYSIS_FLAGS"
    restart: always

  xray-persist:
    image: ${JFROG_DOCKER_REPO}/xray-persist:${XRAY_VERSION}
    container_name: xray-persist
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - "$XRAY_MOUNT_ROOT/xray:/var/opt/jfrog/xray/data"
    environment:
      - "XRAYCONFIGPATH=/var/opt/jfrog/xray/data"
      - "DOCKER_COMPOSE_FLAGS=$DOCKER_COMPOSE_FLAGS"
      - "DOCKER_COMPOSE_XRAY_FLAGS=$DOCKER_COMPOSE_XRAY_PERSIST_FLAGS"
    restart: always

  rabbitmq:
    image: ${JFROG_DOCKER_REPO}/xray-rabbitmq:$RABBITMQ_VERSION
    container_name: xray-rabbitmq
    hostname: $DOCKER_SERVER_HOSTNAME
    volumes:
      - "$XRAY_MOUNT_ROOT/rabbitmq:/var/lib/rabbitmq"
    environment:
      - "RABBITMQ_ERLANG_COOKIE=$RABBITMQ_ERLANG_COOKIE"
    restart: always

  postgres:
    image: ${JFROG_DOCKER_REPO}/xray-postgres:$POSTGRES_VERSION
    container_name: xray-postgres
    environment:
      - "POSTGRES_USER=$POSTGRES_USER"
      - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
      - "POSTGRES_DB=$POSTGRES_DB"
    volumes:
      - "$XRAY_MOUNT_ROOT/postgres:/var/lib/postgresql/data"
    restart: always

  mongodb:
    image: ${JFROG_DOCKER_REPO}/xray-mongo:$MONGO_VERSION
    container_name: xray-mongodb
    entrypoint: /bin/bash -c "chmod 777 /data/logs; /entrypoint.sh --logpath /data/logs/xray-mongo.log --auth"
    volumes:
      - "$XRAY_MOUNT_ROOT/mongodb/logs:/data/logs"
      - "$XRAY_MOUNT_ROOT/mongodb/configdb:/data/configdb"
      - "$XRAY_MOUNT_ROOT/mongodb/db:/data/db"
    restart: always

## ------------------------------------------------------------ Docker networks

#networks:
#  datev-network:
#    name: jfrog-network