version: "3.5"
## -------------------------------------------
## DATEV Specific docker compose configuration
## for JFrog services
## -------------------------------------------
services:

  proxy:
    container_name: reverse-proxy
    image: jwilder/nginx-proxy:${NGINX_VERSION}

    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${XRAY_MOUNT_ROOT}/proxy/conf.d/max_body_size.conf:/etc/nginx/conf.d/max_body_size.conf:ro
      - ${XRAY_MOUNT_ROOT}/proxy/vhost.d:/etc/nginx/vhost.d:ro
    networks:
      jfrog-network:
        aliases:
          - ${JENKINS_HOSTNAME}
          - ${ARTIFACTORY_HOSTNAME}
          - ${ARTIFACTORY_WILDCARD_HOSTNAME}
          - ${XRAY_HOSTNAME}
    ports:
      - 80:80

## ---------------
  artifactory:
    image: ${JFROG_DOCKER_REPO}/artifactory-pro:${ARTIFACTORY_VERSION}
    container_name: artifactory
    ports:
     - ${ARTIFACTORY_SERVER_PORT}:${ARTIFACTORY_SERVER_PORT}
    volumes:
     - ${XRAY_MOUNT_ROOT}/artifactory:/var/opt/jfrog/artifactory
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    networks:
      - jfrog-network
    environment:
      - VIRTUAL_HOST=${ARTIFACTORY_HOSTNAME},${ARTIFACTORY_WILDCARD_HOSTNAME}
      - VIRTUAL_PORT=${ARTIFACTORY_SERVER_PORT}
    

  xray-server:
    image: ${JFROG_DOCKER_REPO}/xray-server:${XRAY_VERSION}
    container_name: xray-server
    ports:
      - ${XRAY_SERVER_PORT}:${XRAY_SERVER_PORT}
    depends_on:
      - mongodb
      - postgres
      - rabbitmq
    volumes:
      - "$XRAY_MOUNT_ROOT/xray:/var/opt/jfrog/xray/data"
    environment:
      - "XRAYCONFIGPATH=/var/opt/jfrog/xray/data"
      - "DOCKER_COMPOSE_FLAGS=$DOCKER_COMPOSE_FLAGS"
      - "DOCKER_COMPOSE_XRAY_FLAGS=$DOCKER_COMPOSE_XRAY_SERVER_FLAGS"
      - VIRTUAL_HOST=${XRAY_HOSTNAME}
      - VIRTUAL_PORT=${XRAY_SERVER_PORT}
    restart: always
    networks:
      - jfrog-network

  xray-indexer:
    image: ${JFROG_DOCKER_REPO}/xray-indexer:${XRAY_VERSION}
    container_name: xray-indexer
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - "$XRAY_MOUNT_ROOT/xray:/var/opt/jfrog/xray/data"
    environment:
      - "XRAYCONFIGPATH=/var/opt/jfrog/xray/data"
      - "DOCKER_COMPOSE_FLAGS=$DOCKER_COMPOSE_FLAGS"
      - "DOCKER_COMPOSE_XRAY_FLAGS=$DOCKER_COMPOSE_XRAY_INDEXER_FLAGS"
    restart: always
    networks:
       - jfrog-network

  xray-analysis:
    image: ${JFROG_DOCKER_REPO}/xray-analysis:${XRAY_VERSION}
    container_name: xray-analysis
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - "$XRAY_MOUNT_ROOT/xray:/var/opt/jfrog/xray/data"
    environment:
      - "XRAYCONFIGPATH=/var/opt/jfrog/xray/data"
      - "DOCKER_COMPOSE_FLAGS=$DOCKER_COMPOSE_FLAGS"
      - "DOCKER_COMPOSE_XRAY_FLAGS=$DOCKER_COMPOSE_XRAY_ANALYSIS_FLAGS"
    restart: always
    networks:
      - jfrog-network

  xray-persist:
    image: ${JFROG_DOCKER_REPO}/xray-persist:${XRAY_VERSION}
    container_name: xray-persist
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - "$XRAY_MOUNT_ROOT/xray:/var/opt/jfrog/xray/data"
    environment:
      - "XRAYCONFIGPATH=/var/opt/jfrog/xray/data"
      - "DOCKER_COMPOSE_FLAGS=$DOCKER_COMPOSE_FLAGS"
      - "DOCKER_COMPOSE_XRAY_FLAGS=$DOCKER_COMPOSE_XRAY_PERSIST_FLAGS"
    restart: always
    networks:
      - jfrog-network

  rabbitmq:
    image: ${JFROG_DOCKER_REPO}/xray-rabbitmq:$RABBITMQ_VERSION
    container_name: xray-rabbitmq
    #hostname: $DOCKER_SERVER_HOSTNAME
    ports:
      - 15672:15672
    volumes:
      - "$XRAY_MOUNT_ROOT/rabbitmq:/var/lib/rabbitmq"
    environment:
      - "RABBITMQ_ERLANG_COOKIE=$RABBITMQ_ERLANG_COOKIE"
      - VIRTUAL_HOST=${XRAY_RABBITMQ_HOSTNAME}
      - VIRTUAL_PORT=15672
    restart: always
    networks:
      jfrog-network:
        aliases:
          - ${XRAY_RABBITMQ_HOSTNAME}

  postgres:
    image: ${JFROG_DOCKER_REPO}/xray-postgres:$POSTGRES_VERSION
    container_name: xray-postgres
    environment:
      - "POSTGRES_USER=$POSTGRES_USER"
      - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
      - "POSTGRES_DB=$POSTGRES_DB"
    volumes:
      - "$XRAY_MOUNT_ROOT/postgres:/var/lib/postgresql/data"
    restart: always
    networks:
      jfrog-network:
        aliases:
          - ${XRAY_POSTGRES_HOSTNAME}

  mongodb:
    image: ${JFROG_DOCKER_REPO}/xray-mongo:$MONGO_VERSION
    container_name: xray-mongodb
    entrypoint: /bin/bash -c "chmod 777 /data/logs; /entrypoint.sh --logpath /data/logs/xray-mongo.log --auth"
    volumes:
      - "$XRAY_MOUNT_ROOT/mongodb/logs:/data/logs"
      - "$XRAY_MOUNT_ROOT/mongodb/configdb:/data/configdb"
      - "$XRAY_MOUNT_ROOT/mongodb/db:/data/db"
    restart: always
    networks:
      jfrog-network:
        aliases:
          - ${XRAY_MONGODB_HOSTNAME}

## ------------------------------------------------------------ Docker networks

networks:
  jfrog-network:
    name: jfrog-network
